config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users , :skip => [:registrations]
  as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
  end

  resources :posts do
    resources :comments
  end
 
  root "posts#index"

  get '/about', to: 'pages#about'
  # this way, you don't have to make it blog/pages/about... it only has to be blog/about

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :name, presence: true, length: {minimum: 3}
  validates :body, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # THIS MAKES IT SO USERS CANNOT REGISTER
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
 
    if @comment.save
      redirect_to post_path(@post)
    else
      flash[:notice] = "The name field must have a minimum of 3 characters and the body field cannot be blank!"
      redirect_to post_path(@post)
    end
    
  end

  def destroy
  	@post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
 
    redirect_to post_path(@post)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
 	end

 	def edit
 		@post = Post.find(params[:id])
 	end

 	def update
 		@post = Post.find(params[:id])
 	  if @post.update(params[:post].permit(:title, :body))
      	redirect_to @post
      else
      	render 'edit'
      end
 	end

 	def destroy
 		@post = Post.find(params[:id])
 		@post.destroy
 		redirect_to root_path
 	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
	end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">

	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time">Commented <%= time_ago_in_words(comment.created_at) %> ago.</p>	
	</div>

	<% if user_signed_in? %> 
	<p><%= link_to 'Delete', [comment.post, comment],
	method: :delete,
	class: "button",
		data: { confirm: 'Are you sure?' } %>
	</p>
	<% end %> 

</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<% if @post.errors.any? %>
<div id="errors">
	<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
	<ul>
		<% @post.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<p><%= f.label :name %><br>
  <%= f.text_field :name %></p>
<p><%= f.label :body %><br>
  <%= f.text_area :body %></p>
<br>
<p><%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
   		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
   		<%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    	<%= csrf_meta_tags %>
  </head>

  <body>
    
    <div id="sidebar">
      	<div id="logo">
        	<%= link_to root_path do %>
          		<%= image_tag "teddy.png" %>
        	<% end %>
      	</div>
 
      	<ul>
        	<li class="category">Theodore X. Li</li>
       		<li><%= link_to "Blog", root_path %></li>
        	<li><%= link_to "About", about_path %> </li>
          <li><a href="http://theodoreli.me">Website</a></li>
      	</ul>
 
      	<ul>
       		<li class="category">Social</li>
          <li><a href="http://facebook.com/thetli8">Facebook</a></li>
          <li><a href="https://twitter.com/thetli8">Twitter</a></li>
       		<li><a href="http://instagram.com/thetli8">Instagram</a></li>
          <li><a href="http://linkedin.com/in/theodorexli">LinkedIn</a></li>
          <li><a href="http://medium.com/@thetli8">Medium</a></li>
       		<li><a href="https://github.com/thetli8">Github</a></li>
          <li><a href="http://challengepost.com/thetli8">ChallengePost</a></li>
          <li><a href="mailto:%74%78%6C%40%75%6D%64%2E%65%64%75">Email</a></li>
      	</ul>

      <% if !user_signed_in? %>
        <p class="sign_in"><%= link_to 'Admin Login', new_user_session_path %></p>
      <% end %>
      
      <% if user_signed_in? %>
        <p class="sign_in"><%= link_to "Change your password", edit_user_registration_path%></p>
      <% end %>
      
    </div>
 		
 	<div id="main_content">
    	<div id="header">
      		<% if current_page?(root_path) %>
            <p>All Posts</p>
          <% elsif current_page?(about_path) %>
            <p>About</p>
          <% else %>
            <%= link_to "Back to All Posts", root_path %>
          <% end %>
 
        <% if user_signed_in? %> 
          <div class="buttons">
            <button class="button"><%= link_to "New Post", new_post_path %></button>
        		<button class="button"><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></button>
      		</div>
        <% end %>
    	</div>
 
    	<% flash.each do |name, msg| %><br>
      	<%= content_tag(:div, msg, class: "alert") %>
   	<% end %>
 
    <%= yield %>

  </div>
 
  </body>


</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpg" %>
  </div>
 
  <div id="content">
    <h1>Theodore X. Li</h1>
    <h2>Nil Volenti Dificile Est.</h2>

    <h5><p>Feel free to visit my <a href="http://theodoreli.me">website</a>, follow me on <a href="http://twitter.com/thetli8">Twitter</a> and <a href="http://instagram.com/thetli8">Instagram</a> or read my editorials on <a href="http://huffingtonpost.com/theodore-li">Huffington Post</a>!
    I am currently a Finance and Computer Science Major at the University of Maryland, College Park.</p></h5>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <p><h6>This website was created using a tutorial made by <a href="http://mackenziechild.me/12-in-12/2/">Mackenzie Child</a>. I created this website to serve two purposes: 1) Learning how to code in <a href="http://rubyonrails.org">Ruby On Rails</a> and 2) Making something useful and cool! <b> Much thanks to Mackenzie Child and the MIT Licenses used for this creation. </b> To learn more about this project, please feel free to contact me with the Email link.</b> </h6></p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
 
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<!-- do loop so it will show this on the start of it -->

<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
    <!-- so it will show a date it was created, different from the show page, includes the actual date -->
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
<h1>New Post</h1>
 <%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


  	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
  	<%= f.submit %>
  	</p>

<% end %>

app/views/posts/show.html.erb
<!-- Adds title in an <h1> tag with the class of the title -->

<div id="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<!-- Adds the time the post was created at -->
	<p class="date">
		<% if user_signed_in? %>
		Submitted <%= time_ago_in_words(@post.created_at) %> ago.
		| <%= link_to 'Edit', edit_post_path(@post) %> |
		<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %> 
	</p>

	<!-- Adds the body content -->
	<p class="body">
		<%= @post.body %>
	</p>
	
	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>
		
		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	</div>
</div>